name: CI v0.5

on:
  schedule:
    - cron: '0 5 * * *'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        fleet_version:
          - v0.3.9
          - v0.4.0
          - v0.5.0

    steps:
      -
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "release/v0.5"
      -
        uses: actions/cache@v3
        id: fleet-cli-cache
        with:
          path: /home/runner/.local/bin
          key: ${{ runner.os }}-fleet-cli-${{ matrix.fleet_version }}
      -
        name: Download CLI
        if: steps.fleet-cli-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p /home/runner/.local/bin
          wget -nv "https://github.com/rancher/fleet/releases/download/${{ matrix.fleet_version }}/fleet-linux-amd64"
          mv fleet-linux-amd64 /home/runner/.local/bin/fleet
          chmod +x /home/runner/.local/bin/fleet
      -
        name: Test
        run: |
          tests/test.sh
